{
 "title": "power_and_sci_dashboard",
 "description": "Grafana dashboard for power consumption and software carbon intensity measurements",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Software monitored",
   "type": "stat",
   "description": "The number of software measured",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "target" ], "type": "tag" }
     ],
     "measurement": "power_consumption",
     "query": "SELECT count(distinct(\"target\")) from (SELECT \"sci\" FROM \"autogen\".\"power_consumption\" WHERE $timeFilter GROUP BY \"target\")",
     "select": [
      [
       { "params": [ "sci" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Energy",
   "type": "stat",
   "description": "Total energy consumed within the last time interval",
   "gridPos": { "h": 9, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "target" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_consumption",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 9, "w": 10, "x": 7, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:left;\"><img src=\"https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/images/hackathon-banner.png?raw=true\" style='height: 100%; width: 100%; object-fit: contain'></div>"
   }
  },
  {
   "title": "Total SCI",
   "type": "stat",
   "description": "Total energy consumed within the last time interval",
   "gridPos": { "h": 9, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "per R" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "target" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_consumption",
     "select": [
      [
       { "params": [ "sci" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current emission",
   "type": "stat",
   "description": "Average 5mins emission withing time interval",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "CO2/KWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_consumption",
     "select": [
      [
       { "params": [ "emission" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Software Carbon Intensity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "target" ], "type": "tag" }
     ],
     "measurement": "power_consumption",
     "query": "SELECT power FROM \"power_consumption\"",
     "select": [
      [
       { "params": [ "sci" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "target" ], "type": "tag" }
     ],
     "measurement": "power_consumption",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}