name: using CarboneAware Github action in sample pipeline

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'src/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CarboneAWare metrics
      id: carboneaware-metrics
      uses: Green-Software-Foundation/carbon-aware-sdk@sdkCLI-githubaction  # here "sdkCLI-githubaction" is the name of the branch
      with:
        location: westeurope,francecentral,westus
        #config: /carbon-aware.json
        #fromTime:
        #toTime:
        
    - name: Deplpoy Workload to Selected Region
      run: echo deploying ML Training Job to Region "${{ steps.carboneaware-metrics.outputs.LowestEmissionsLocation}}"
